name: Greetings and Deploy

on: 
  pull_request_target:
  issues:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "You just created your first issue."
        pr-message: "You just created your first pull request"

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Print current working directory
      run: pwd

    - name: Change directory and install dependencies
      run: cd ./my-app && npm ci
      
    - name: Change directory and run tests
      run: cd ./my-app && npm test
    
    - name: Deploy to Vercel
      run: cd ./my-app && npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
    
    - name: Report Deployment Status
      run: |
      curl -X POST -H "Accept: application/vnd.github.v3+json" \
      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$GITHUB_RUN_ID/statuses" \
      -d '{
        "state": "success",
        "environment": "Production – deliverable",
        "environment_url": "https://my-gd7ipt2n2-veenc0.vercel.app"
      }'